name: test

on: [workflow_dispatch, push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge install
        run: |
          forge --version
          forge install
        id: install
      
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15
      
      - name: Install GMX dependencies
        run: |
          cd lib/gmx-synthetics
          yarn

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge tests
        env:
          ARBITRUM_GOERLI_URL: ${{ secrets.ARBITRUM_GOERLI_URL }}
          DATA_STORE:  ${{ vars.DATA_STORE }}
          READER:  ${{ vars.READER }}
          ORDER_HANDLER:  ${{ vars.ORDER_HANDLER }}
          DEPOSIT_HANDLER:  ${{ vars.DEPOSIT_HANDLER }}
          WITHDRAWAL_HANDLER:  ${{ vars.WITHDRAWAL_HANDLER }}
          MARKET_FORK_TEST_FEED_ID_0:  ${{ vars.MARKET_FORK_TEST_FEED_ID_0 }}
          MARKET_FORK_TEST_FEED_ID_1:  ${{ vars.MARKET_FORK_TEST_FEED_ID_1 }}
          MARKET_ADDRESS_0: ${{ vars.MARKET_ADDRESS_0 }}
          MARKET_ADDRESS_1: ${{ vars.MARKET_ADDRESS_1 }}
        run: |
          forge test -vvv
        id: test
